package com.example.bot.service;

import org.springframework.stereotype.Service;

import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import java.io.*;

@Service
public class PcmToMp3Converter {

    //This basically done to convert the voice which is generated by Gemini to workable format
    public static byte[] convertPcmToWav(byte[] pcmData, int sampleRate, int channels) throws Exception {
        AudioFormat format = new AudioFormat(sampleRate, 16, channels, true, false);
        try (ByteArrayInputStream bais = new ByteArrayInputStream(pcmData);
             AudioInputStream pcmStream = new AudioInputStream(bais, format, pcmData.length / format.getFrameSize());
             ByteArrayOutputStream wavOut = new ByteArrayOutputStream()) {

            AudioSystem.write(pcmStream, AudioFileFormat.Type.WAVE, wavOut);
            return wavOut.toByteArray();
        }
    }

}
